---
- name: create user in Ubuntu....
  hosts: all
  become: yes
  tasks:
    - name: Ensure group "wheel" exists
      group:
        name: wheel
        state: present
    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: "^%wheel"
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"

    - name: Add sudoers users to wheel group
      user: name=hadoop groups=wheel append=yes state=present createhome=yes

    - name: Set up authorized keys for the hadoop user
      authorized_key: user=hadoop key="{{item}}"
      with_file:
        - /home/pe/.ssh/id_rsa.pub
